// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRVGAeTrTgR1SnOOnnyp7it_oUyknQCRg',
    appId: '1:367425490626:web:7098522ea93a6caa29755b',
    messagingSenderId: '367425490626',
    projectId: 'utter-411c1',
    authDomain: 'utter-411c1.firebaseapp.com',
    storageBucket: 'utter-411c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsbaMgbpIpyqMfOOYVfI3n5Qn_1T9U_I',
    appId: '1:367425490626:android:5e52bb9201456dfb29755b',
    messagingSenderId: '367425490626',
    projectId: 'utter-411c1',
    storageBucket: 'utter-411c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2Y9KK8Lm96kr7meKmYibdPnEwMugGzE',
    appId: '1:367425490626:ios:72f740c4e58a3e9529755b',
    messagingSenderId: '367425490626',
    projectId: 'utter-411c1',
    storageBucket: 'utter-411c1.appspot.com',
    iosClientId: '367425490626-epldlukifltm0hc5plmqie6o0c46bl1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.utter',
  );
}
